//字符串常量文件主要用来做ACTION的名字
export const ARTICLE_REFRESH='ARTICLE_REFRESH'
export const ARTICLE_REFRESHED='ARTICLE_NORMAL'
export const ARTICLE_MORE='ARTICLE_MORE'
export const ARTICLE_NORMAL='ARTICLE_NORMAL'